### ISSUE TITLE
TypeError: Cannot read property 'light' of undefined

### ISSUE THREAD

**Issue by loic-lopez** [react-navigation/drawer#101]
When using `jest.mock("react-navigation-drawer")`

An error is thrown:
```
● Test suite failed to run

    TypeError: Cannot read property 'light' of undefined

      at Object.DrawerNavigator (node_modules/react-navigation-drawer/lib/commonjs/navigators/createDrawerNavigator.tsx:62:7)
      at Object.<anonymous> (node_modules/react-navigation-drawer/lib/commonjs/index.tsx:19:1)
```

**Comment by abjacs** [comment]
Make sure you're on the right version of **react-navigation**.
Per the documentation:
```
Note: support for built-in themes requires react-navigation@>=3.12.0!
```
https://reactnavigation.org/docs/en/themes.html

**Comment by jefflewis** [comment]
I fixed this by updating my react-navigation mock to include the theme colors.

```ts
jest.mock("react-navigation", () => {
  return {
    createAppContainer: jest
      .fn()
      .mockReturnValue(function NavigationContainer(props) {
        return null;
      }),
    createDrawerNavigator: jest.fn().mockImplementation(nav => {
      return {};
    }),
    createMaterialTopTabNavigator: jest.fn(),
    createStackNavigator: jest.fn().mockImplementation(nav => {
      return {};
    }),
    createSwitchNavigator: jest.fn().mockImplementation(nav => {
      return {};
    }),
    createBottomTabNavigator: jest.fn(),
    withNavigation: jest.fn().mockImplementation(component => component),
    StackActions: {
      push: jest
        .fn()
        .mockImplementation(x => ({ ...x, type: "Navigation/PUSH" })),
      replace: jest
        .fn()
        .mockImplementation(x => ({ ...x, type: "Navigation/REPLACE" }))
    },
    NavigationActions: {
      navigate: jest.fn().mockImplementation(x => x)
    },
    ThemeColors: {
      light: {
        bodyContent: ""
      },
      dark: {
        bodyContent: ""
      }
    }
  };
});
```
